config/routes.rb
AjaxConnection::Application.routes.draw do
  resources :people

  resources :relationships

  root :to => "people#index"

end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :name, :email, :info
  
  validates :name, :presence => true
  validates :email, :presence => true,
                    :uniqueness => { :case_sensitive => false }
                    
  has_many :relationships, :foreign_key => 'client_id',
                           :dependent => :destroy
  has_many :supportees, :through => :relationships, :source => :prospect
  
  has_many :reverse_relationships, :foreign_key => 'prospect_id',
                                   :class_name => 'Relationship',
                                   :dependent => :destroy
  has_many :supporters, :through => :reverse_relationships, :source => :client
  
  def supporting?(prospect)
    relationships.find_by_prospect_id(prospect)
  end
  
  def support!(prospect)
    relationships.create!(:prospect_id => prospect.id)
  end
    
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :prospect_id, :info
  
  belongs_to :client, :class_name => "Person"
  belongs_to :prospect, :class_name => "Person"
  
  validates :client_id, :presence => true
  validates :prospect_id, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.xml
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @people }
    end
  end

  # GET /people/1
  # GET /people/1.xml
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @person }
    end
  end

  # GET /people/new
  # GET /people/new.xml
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.xml
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to(@person, :notice => 'Person was successfully created.') }
        format.xml  { render :xml => @person, :status => :created, :location => @person }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.xml
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to(@person, :notice => 'Person was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.xml
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to(people_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  # GET /relationships
  # GET /relationships.xml
  def index
    @relationships = Relationship.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @relationships }
    end
  end

  # GET /relationships/1
  # GET /relationships/1.xml
  def show
    @relationship = Relationship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @relationship }
    end
  end

  # GET /relationships/new
  # GET /relationships/new.xml
  def new
    @relationship = Relationship.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @relationship }
    end
  end

  # GET /relationships/1/edit
  def edit
    @relationship = Relationship.find(params[:id])
  end

  # POST /relationships
  # POST /relationships.xml
  def create
    @relationship = Relationship.new(params[:relationship])

    respond_to do |format|
      if @relationship.save
        format.html { redirect_to(@relationship, :notice => 'Relationship was successfully created.') }
        format.xml  { render :xml => @relationship, :status => :created, :location => @relationship }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @relationship.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /relationships/1
  # PUT /relationships/1.xml
  def update
    @relationship = Relationship.find(params[:id])

    respond_to do |format|
      if @relationship.update_attributes(params[:relationship])
        format.html { redirect_to(@relationship, :notice => 'Relationship was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @relationship.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /relationships/1
  # DELETE /relationships/1.xml
  def destroy
    @relationship = Relationship.find(params[:id])
    @relationship.destroy

    respond_to do |format|
      format.html { redirect_to(relationships_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
  def tab_id(tab_order, connection)
    "tabs-#{tab_order}#{connection.client.id}#{connection.prospect.id}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8"/>
  <title>JQurey UI</title>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.0/jquery.min.js"></script>
  <%= stylesheet_link_tag 'scaffold', 'less', 'application', 'redmond/jquery-ui-1.8.9.custom' %>
  <%= javascript_include_tag 'rails', 'application', 'jquery-ui-1.8.9.custom.min' %>
  <%= csrf_meta_tag %>
</head>
<body>

<section id="page">
	<%= yield %>
</section>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :info %><br />
    <%= f.text_area :info %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/_person.html.erb
<li>
	<%= person.name %>
  <ul>
    <li><%= person.email %></li>
    <li><%= person.info %></li>
  </ul>
</li>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
		<th>Name</th>
    <th>Email</th>
    <th>Info</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.name %></td>
    <td><%= person.email %></td>
    <td><%= person.info %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<header>
	<h1><%= @person.name %></h1>
</header>

<%= @person.email %>

<p>
  <strong>Info:</strong>
  <%= @person.info %>
</p>

<section id="supporting">
	<h2>Supportees List</h2>
	<div id="accordion">
		<%= render :partial => 'relationships/relationship', :collection => @person.relationships %>
		</div>
</section>

<section id="connections-list">
	<h2>Connections List</h2>
		<%= render :partial => 'relationships/connection', :collection => @person.relationships %>
</section>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/relationships/_connection.html.erb
<div class="tabs">
	<ul>
		<li><%= link_to connection.client.name, "##{tab_id(1,connection)}" %></li>
		<li><%= link_to 'Connection Info', "##{tab_id(2,connection)}" %></li>
		<li><%= link_to connection.prospect.name, "##{tab_id(3,connection)}" %></li>
	</ul>

	<%= tag 'div', :id=>"#{tab_id(1,connection)}" %>
	 	<ul>
			<li>
				<strong>Email:</strong> <%= connection.client.email %>
			</li>
			<li>
				<strong>Info: </strong> <%= connection.client.info %>
			</li>
		</ul>
	</div>

	<%= tag 'div', :id=>"#{tab_id(2,connection)}" %>
		<ul>
	 		<li><%= connection.info %></li>
		</ul>
	</div>

	<%= tag 'div', :id=>"#{tab_id(3,connection)}" %>
		<ul>
			<li>
				<strong>Email:</strong> <%= connection.prospect.email %>
			</li>
			<li>
				<strong>Info: </strong> <%= connection.prospect.info %>
			</li>
		</ul>
	</div>	
</div>

app/views/relationships/_form.html.erb
<%= form_for(@relationship) do |f| %>
  <% if @relationship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relationship.errors.count, "error") %> prohibited this relationship from being saved:</h2>

      <ul>
      <% @relationship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_id %><br />
    <%= f.text_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :prospect_id %><br />
    <%= f.text_field :prospect_id %>
  </div>
  <div class="field">
    <%= f.label :info %><br />
    <%= f.text_area :info %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relationships/_relationship.html.erb
		<div>
			<h3>
				<%= link_to relationship.prospect.name, relationship.prospect %>
			</h3>

			<div class="body">
		  	<ul class="supportee-info">
					<li>
						<strong>Email:</strong> <%= relationship.prospect.email %>
					</li>
					<li>
						<strong>Info: </strong> <%= relationship.prospect.info %>
					</li>
				</ul>
				<ul class="relationship-info">
		  		<li><%= relationship.info %></li>
				</ul>
			</div>
		</div>

app/views/relationships/edit.html.erb
<h1>Editing relationship</h1>

<%= render 'form' %>

<%= link_to 'Show', @relationship %> |
<%= link_to 'Back', relationships_path %>

app/views/relationships/index.html.erb
<h1>Listing relationships</h1>

<table>
  <tr>
    <th>Client</th>
    <th>Prospect</th>
    <th>Info</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @relationships.each do |relationship| %>
  <tr>
    <td><%= relationship.client.name %></td>
    <td><%= relationship.prospect.name %></td>
    <td><%= relationship.info %></td>
    <td><%= link_to 'Show', relationship %></td>
    <td><%= link_to 'Edit', edit_relationship_path(relationship) %></td>
    <td><%= link_to 'Destroy', relationship, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Relationship', new_relationship_path %>

app/views/relationships/new.html.erb
<h1>New relationship</h1>

<%= render 'form' %>

<%= link_to 'Back', relationships_path %>

app/views/relationships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Client:</b>
  <%= @relationship.client_id %>
</p>

<p>
  <b>Prospect:</b>
  <%= @relationship.prospect_id %>
</p>

<p>
  <b>Info:</b>
  <%= @relationship.info %>
</p>


<%= link_to 'Edit', edit_relationship_path(@relationship) %> |
<%= link_to 'Back', relationships_path %>